# Generated by Django 3.1.4 on 2024-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0014_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='font',
            field=models.CharField(blank=True, choices=[('AR', 'Arial'), ('VR', 'Verdana'), ('TM', 'Times New Roman'), ('SC', 'Scriptina'), ('ED', 'Edwardian Script'), ('GV', 'Great Vibes'), ('AB', 'Alex Brush'), ('SR', 'Snell Roundhand'), ('MC', 'Monotype Corsiva'), ('PS', 'Pinyon Script'), ('ST', 'Satisfy'), ('TG', 'Tangerine'), ('AL', 'Allura')], default='AR', max_length=2),
        ),
    ]
